# Generated by Django 5.0 on 2023-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
